<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RecruitmentPortal.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Dapper micro-ORM -->
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <!-- SQL Server client (mssqlclient) -->
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <!-- JWT authentication -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.2" />
    <!-- Swagger / OpenAPI -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
  </ItemGroup>

</Project>
